apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobradarai-web
  namespace: jobradarai
  labels:
    app.kubernetes.io/name: jobradarai-web
    app.kubernetes.io/part-of: jobradarai
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: jobs.raphcvr.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobradarai-web
                port:
                  name: http
